### ISSUE TITLE
run ptudes flyby command issue

### ISSUE THREAD

**Issue by MaxikKot** [bexcite/ptudes-lab#13]
Hello. First of all I want to thank you for this source code!
However, I can't process Ouster sensor raw data (.pcap format) with "ptudes flyby ./OS-0-128_v3.0.1_1024x10.pcap --kitti-poses ./OS-0-128_v3.0.1_poses_kitti.txt" command.  Аs a result I get the following error output:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\1\AppData\Local\Programs\Python\Python311\Scripts\ptudes.exe\__main__.py", line 4, in <module>
  File "C:\Users\1\AppData\Local\Programs\Python\Python311\Lib\site-packages\ptudes\cli\run.py", line 3, in <module>
    from ptudes.cli.flyby import ptudes_flyby
  File "C:\Users\1\AppData\Local\Programs\Python\Python311\Lib\site-packages\ptudes\cli\flyby.py", line 6, in <module>
    import ouster.client as client
ModuleNotFoundError: No module named 'ouster.client'

although the client version 0.12.0 is installed.
I’ll be grateful if you guide me and tell me what I’m doing wrong. Best regards, Max

**Comment by atorizva** [comment]
Hello, I was also experiencing the same issue. It appears Ouster SDK v0.12.0 isn't compatible with the latest version. I test it out with `ouster-sdk==0.10.0` and it works fine. Just change the version in `setup.py`, install the package again and you are good to go.

**Comment by bexcite** [comment]
@MaxikKot thanks for bringin it up, yes, ouster-sdk 0.12.0 and kiss-icp 1.0.0 not supported (they released later and did some changes in their API), but I'm working on fixes and hope to publish the fixed version in 1-2 days. I'll update here when new version will be available.

Thanks!

**Comment by bexcite** [comment]
The issue fixed: https://github.com/bexcite/ptudes-lab/pull/14
And published to PyPi: https://pypi.org/project/ptudes-lab/#history (make sure the version 0.0.5 is installed).

And also make sure to follow the message so ouster-sdk and kiss-icp will result in a correct version, there are some mess with versions due to ouster-sdk pinning kiss-icp :(

```
The ouster-sdk package is not installed on your system. The required version
is 0.11.0 or higher.

Please install it manually by running two commands one by one, disregard any errors:

pip3 install 'ouster-sdk>=0.11.0'
pip3 install 'kiss-icp>=1.0.0'

Check versions of kiss-icp and ouster-sdk installed and make sure they are in the
range of above commands:

pip3 list

NOTE: We have not included ouster-sdk in the project dependencies because it
      requires kiss-icp==0.4.0, which is not compatible with this project.
      This project supports the latest version of kiss-icp (1.0.0 or higher)
      and ouster-sdk>=0.11.0.
```

**Comment by MaxikKot** [comment]
@bexcite Thank you very much for your work and efficiency!
